{% set name = "ligo-common" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: 17baa0794a0ef411d58b587968eeed22e00b7cbdebd9d310b5801ec8ccc9f9f9

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - ligo

about:
  home: https://git.ligo.org/lscsoft/ligo-common
  dev_url: https://git.ligo.org/lscsoft/ligo-common
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Base package for `ligo` python namespace

extra:
  recipe-maintainers:
    - duncanmmacleod
