{% set version = "1.0.4" %}

package:
  name: ligo-common
  version: {{ version }}

source:
  fn: ligo-common-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/ligo-common-{{ version }}.tar.gz
  md5: 142c2e287cc09bd0192c916a0be6e492
  sha256: 17baa0794a0ef411d58b587968eeed22e00b7cbdebd9d310b5801ec8ccc9f9f9

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - ligo

about:
  home: https://git.ligo.org/lscsoft/ligo-common
  license: GPLv3
  license_file: LICENSE
  summary: Base package for `ligo` python namespace

extra:
  recipe-maintainers:
    - duncanmmacleod
