travis:
  secure:
    BINSTAR_TOKEN: qV7/V6H2f7JWn9O1zbDxZ428xDKtUcC0pVksX4ydrY50erFVHM5fRl/i0+n6DRZwjqWo7+VEPvLje+WwGp74OHasePUzcUoK6jeD855P2c2clocEmcvlUuf8MLyMTMfRZ4Ta/k9v+FFTHxQhT4IeGihpzZrJAFPt1+WRW1wsVODdwaaEZ1NXxuLxPJtGU6CTxEc/m+p1FZXiv+Jd+nNQQP77xB1FAIBuoxpRFSfEA1H6p4UJKTlV2uQmKJ7K1Nms1i1ODTRXNPkCp3FZoYhVxdSVBpXcARSM4FC9znzun6QVl+NAvFS62BJQwJ0QZ2NCoRJ3F2UrcIBJseEZkRnTspl3Loe6mSIGzwi4X19SsihbR8mm7vhMQombcV/orAD9ZiAJf0TQTa5Q+waP7OAWMdTqKHPoW2FCpnP7Ce0ASwdozVxgFJv2jizlW2bBGaH0SC8BbfckcQRR7LBPeJMp60AWmfOyslCY9WTX95LZ5fLKapPTgMyn14hcXLDfL+Nhl81edA1ZYNJiOgBMR2rpk+l+CYORdpR616CAyAT59CdKZV3d0YWkdq2WC3MV7GJraTrgR1KaUImHixi2i6CbsMiMCVj1uFa3Ms4gbNfVwX0OwmVw97nK8W4ysWbVQvWV0+cfA81L4LkXjNmVtTzGB0iqxYOirvwOA6yx+pKZh9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
