travis:
  secure:
    BINSTAR_TOKEN: rbpKOw7G3JI0KxQZlbL1QtuZyYLXjgtcAjyRAo75NmN5AtNaD2ZttbWNH7fs9K94nLoaAXvwpp8mr2HL8vOqTLjd8Ew0bhtX4FUU8hVk8VoTLQoOGTt9qnc6tuveGS2DWrYMulVhQcLzjunyTbpAq7HoYmuovU474qhNQla86RvmLynIVr4v3N/UANp9vcUrUQiGpyn+uhtoYK9/ZmnpWaE8BW2i1TH5iTwhGsQDkwvC81iSCX9O2xeeITYKyL6fdpHPiiDX94iKbTHlVqUbLqPtzET1B8vrnOnpIGOitGM0y3KCZexCGWmbHcnzQLLXuGQjXQ0M8XCtolCALRLJ9Pvxt6IvjpARERqE+dk1hoNf+jMm3qR0q9Xfahue1B2giH3JLVYOu2f+AnSoWG0Wzt3KoORKAPlkENHR+O4/9z1HwGfzZQa0nHwfjEg04tS0zgruc6fVH+jwqplDKxvRomEpCoW6UAXbsSn3y4opwk9BNqHVABOHSawP+SKvW13VJ1+qD1+fUG983dOmkk4jZ+MBAjLIgf8wk8EzTWCUXEvPUMMy+6sL7trhJGjU0Y3SSYsziYyWFK0217Ty98wFjJHJYZjwLHKgRSz0PhLz5PGA0pp7+1wjPzABHdYZldUgHOEncbjMWV+WAo56jrphPazlsAibEblPAgelSfiPuH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
